#!/bin/sh
echo Setting the branches for wickr-wickrio, sdk, core and integrations

export WICKRWICKRIOBRANCH="prealpha_v4.52"
export WICKRSDKBRANCH="v4.52"
export WICKRCOREBRANCH="Desktop_v4.52"
export WICKRINTEGRATIONSBRANCH="alpha"
