#!/bin/sh
echo Setting the branches for wickr-wickrio, sdk, core and integrations

export WICKRWICKRIOBRANCH="paul-5.10.1"
export WICKRSDKBRANCH="bot_4.54"
export WICKRCOREBRANCH="bot_4.54"
export WICKRINTEGRATIONSBRANCH="alpha"
