#!/bin/sh
echo Setting the branches for wickr-wickrio, sdk, core and integrations

export WICKRWICKRIOBRANCH="paul-5.10.1"
export WICKRSDKBRANCH="alpha"
export WICKRCOREBRANCH="alpha"
export WICKRINTEGRATIONSBRANCH="alpha"
