FROM ubuntu:16.04

MAINTAINER "wickr" <info@wickr.com>
# Variables
ENV HOME /home/ubuntu

WORKDIR $HOME

# Make port 4001 available: used for API requests
EXPOSE 4001
# Make port 5001 available: used for connections from core or services
EXPOSE 5001

COPY packages/QTDEBFILE ./QTDEBFILE
COPY packages/INTEGRATIONDEBFILE ./INTEGRATIONDEBFILE
COPY packages/BOTDEBFILE ./BOTDEBFILE
COPY packages/CONSOLEDEBFILE ./CONSOLEDEBFILE

ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update \
  && apt-get upgrade \
  && apt-get install wget \
  && wget http://packages.erlang-solutions.com/site/esl/esl-erlang/FLAVOUR_1_general/esl-erlang_20.1-1~ubuntu~xenial_amd64.deb \
  && sudo dpkg -i esl-erlang_20.1-1\~ubuntu\~xenial_amd64.deb \
  && apt-get -f install \
  && echo "deb https://dl.bintray.com/rabbitmq/debian xenial main" | sudo tee /etc/apt/sources.list.d/bintray.rabbitmq.list \
  && wget -O- https://www.rabbitmq.com/rabbitmq-release-signing-key.asc | sudo apt-key add - \
  && apt-get update \
  && apt-get install rabbitmq-server \
  && apt-get install -y --no-install-recommends apt-utils \
  && apt-get -y install gdebi \
  && apt-get -y install libsqlcipher.dev \
  && gdebi -n QTDEBFILE \
  && gdebi -n INTEGRATIONDEBFILE \
  && gdebi -n BOTDEBFILE \
  && gdebi -n CONSOLEDEBFILE
ARG DEBIAN_FRONTEND=readline

COPY start.sh ./start.sh

# Start the processes
CMD ["./start.sh"]
