FROM ubuntu:16.04

MAINTAINER "wickr" <info@wickr.com>
# Variables
ENV HOME /home/ubuntu

WORKDIR $HOME

# Make port 4001 available: used for API requests
EXPOSE 4001
# Make port 5001 available: used for connections from core or services
EXPOSE 5001

COPY packages/QTDEBFILE ./QTDEBFILE
COPY packages/DOCKERDEBFILE ./DOCKERDEBFILE

ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update \
  && apt-get install -y --no-install-recommends wget \
  && wget http://packages.erlang-solutions.com/site/esl/esl-erlang/FLAVOUR_1_general/esl-erlang_20.1-1~ubuntu~xenial_amd64.deb \
  && apt-get install -y --no-install-recommends gdebi gnupg \
  && gdebi -n esl-erlang_20.1-1\~ubuntu\~xenial_amd64.deb \
  && echo "deb https://dl.bintray.com/rabbitmq/debian xenial main" | tee /etc/apt/sources.list.d/bintray.rabbitmq.list \
  && wget -O- https://www.rabbitmq.com/rabbitmq-release-signing-key.asc | apt-key add - \
  && apt-get update \
  && apt-get install -y --no-install-recommends rabbitmq-server \
  && apt-get install -y --no-install-recommends apt-utils \
  && apt-get install -y --no-install-recommends libsqlcipher.dev \
  && apt-get install -y curl \
  && curl -sL https://deb.nodesource.com/setup_9.x | bash - \
  && apt-get install -y nodejs \
  && npm install -g coffeescript pm2 coffee-script axios prompt fs path \
  && apt-get install -y openssl \
  && gdebi -n QTDEBFILE \
  && gdebi -n DOCKERDEBFILE
ARG DEBIAN_FRONTEND=readline

COPY start.sh ./start.sh

# Start the processes
CMD ["./start.sh"]

