#ifndef WICKRIORETURNCODES_H
#define WICKRIORETURNCODES_H

#define WIOPROVISION_SUCCESS            0
#define WIOPROVISION_USER_EXISTS        1
#define WIOPROVISION_USER_NOT_FOUND     2
#define WIOPROVISION_BAD_CREDENTIALS    3
#define WIOPROVISION_FAILED             4

#endif // WICKRIORETURNCODES_H
