#!/bin/bash

set -e

case "$1" in
    upgrade)
        echo "Pre-install upgrade for old version of WickrIO Test Bot:"

        #
        # Stop the WickrIO service
        #
        set +e
        systemctl stop WickrIOSvrINSTALLEXT
        # Remove the startup entry for the service(s)
        update-rc.d -f WickrIOSvrINSTALLEXT remove
        set -e

        #
        # Stop the WickrIO Console service
        #
        set +e
        systemctl stop WickrIOCSvrINSTALLEXT
        # Remove the startup entry for the service(s)
        update-rc.d -f WickrIOCSvrINSTALLEXT remove
        set -e

    ;;
esac    


exit 0
