#!/bin/bash

set -e

case "$1" in
    configure)
        echo "Post-install configure for new version of WickrIO Test Bot:"

        # TODO: Should only have to restart if the service was already running!

    ;;
esac

exit 0
