#!/bin/sh

# a second stage deploy script...
#
# Arguments to this script:
# $1 = build directory
# $2 = build number
# $3 = build extension string (i.e. alpha)
# $4 = build installation string (i.e. Alpha)
# $5 = release build flag (true for release)
# $6 = Output directory

set -e
current=`dirname $0`
cd $current

build_dir=$1
build_number=$2
build_extension=$3
install_extension=$4
release_flag=$5

if test -z "$release_flag" ; then
	release_flag="false"; fi

if test -z "$output_dif" ; then
    output_dir="/dev/null" ; fi

#
# Debug display of input
#
echo build_dir=$build_dir
echo build_number=$build_number
echo build_extension=$build_extension
echo install_extension=$install_extension
echo release_flag=$release_flag

#
# Setup the version number(s)
#
maj=`echo $build_number | cut -c1-2 | sed 's/^0*//'`
min=`echo $build_number | cut -c3-4`
pat=`echo $build_number | cut -c5-6`
bld=`echo $build_number | cut -c7-8`

if [ "$release_flag" = "true" ]; then
	bldtype=""
	BldType=""
	version="${maj}.${min}.${pat}-${bld}"
else
	bldtype="-${build_extension}"
	BldType=$install_extension
	version="${maj}.${min}.${pat}-${bld}~${build_extension}"
fi


#
# More debug output
#
echo bldtype=$bldtype
echo BldType=$BldType
echo version=$version

prefix=~/tmp/wio_services${bldtype}-deb
debian=~/tmp/wio_services${bldtype}-deb/DEBIAN
bindir=$prefix/usr/bin
sbindir=$prefix/usr/sbin
libdir=$prefix/usr/lib/wio_services${bldtype}
docdir=$prefix/usr/share/doc/wio_services${bldtype}
plugins=$prefix/usr/lib/wio_services${bldtype}/plugins

# Service related definitions
svcinitdir=$prefix/etc/init.d
systemdlibdir=$prefix/lib/systemd/system

optdir=$prefix/opt/WickrIO$BldType
scriptsdir=$optdir/scripts
imagedir=$optdir/attachments/image

platform=$current/../../../../platforms/linux/generic-64
support=$current/../support

# Client definitions
menus=$prefix/usr/share/applications
pixmaps=$prefix/usr/share/pixmaps
messages=$prefix/usr/share/indicators/messages/applications
appdata=$prefix/usr/share/appdata

# Cleanup the target location (i.e. remove the target directory)
rm -rf $prefix

# Create the appropriate directories in the target location
mkdir -p $debian
mkdir -p $bindir
mkdir -p $sbindir
mkdir -p $docdir
mkdir -p $libdir
mkdir -p $optdir
mkdir -p $scriptsdir
mkdir -p $imagedir
#mkdir -p $crondir
mkdir -p $plugins/sqldrivers
mkdir -p $svcinitdir
mkdir -p $systemdlibdir

# Client directories
mkdir -p $pixmaps
mkdir -p $menus
mkdir -p $appdata

#
# Copy the executables
#
cp -a $current/../../../../../${build_dir}/services/settings_init/wickrio_settings_init $bindir/wickrio_settings_init${bldtype}
cp -a $current/../../../../../${build_dir}/services/service_control/wickrio_service_control $bindir/wickrio_service_control${bldtype}
cp -a $current/../../../../../${build_dir}/services/console/WickrIOConsole$BldType $bindir
cp -a $current/../../../../../${build_dir}/services/consoleserver/WickrIOCSvr$BldType $sbindir
cp -a $current/../../../../../${build_dir}/services/clientserver/WickrIOSvr$BldType $sbindir

# only for Beta version
cp -a $current/../../../../../${build_dir}/services/callback_listener/WickrIOCallbackListener$BldType $bindir

if [ "$release_flag" = "true" ]; then
  cp -a $current/../../../../../${build_dir}/libs/QtWebApp/libQtWebApp.* $libdir
  cp -a $current/../../../../../${build_dir}/libs/WickrIOLib/libWickrIOLib.* $libdir
  cp -a $current/../../../../../${build_dir}/libs/WickrIOGUI/libWickrIOGUI.* $libdir
else
  cp -a $current/../../../../../${build_dir}/libs/QtWebApp/libQtWebAppd.* $libdir
  cp -a $current/../../../../../${build_dir}/libs/WickrIOLib/libWickrIOLibd.* $libdir
  cp -a $current/../../../../../${build_dir}/libs/WickrIOGUI/libWickrIOGUId.* $libdir
fi
cp -a $current/../../../../../${build_dir}/libs/SMTPEmail/libSMTPEmail.* $libdir

#TODO: Add any chrpath here if needed

#
# Copy support files.
# Change the contents appropriately for Beta version Release versions
#
sed -e "s/EXTENSION/${bldtype}/g" -e "s/INSTALLEXT/${BldType}/g" -e "s/VERSION/$version/" <$current/control64 > $debian/control

# Installer pre and post installation scripts
sed -e "s/EXTENSION/${bldtype}/g" -e "s/INSTALLEXT/${BldType}/g" <$current/preinst > $debian/preinst
sed -e "s/EXTENSION/${bldtype}/g" -e "s/INSTALLEXT/${BldType}/g" <$current/postinst > $debian/postinst
sed -e "s/EXTENSION/${bldtype}/g" -e "s/INSTALLEXT/${BldType}/g" <$current/prerm > $debian/prerm

# WickrIO Client Server settings file
sed -e "s/EXTENSION/${bldtype}/g" -e "s/INSTALLEXT/${BldType}/g" <$current/WickrIOSvr.ini > $optdir/WickrIOSvr$BldType.ini

# Daemon init script
sed -e "s/EXTENSION/${bldtype}/g" -e "s/INSTALLEXT/${BldType}/g" <$current/WickrIOSvr.script > $svcinitdir/WickrIOSvr$BldType

# Daemon init script
sed -e "s/EXTENSION/${bldtype}/g" -e "s/INSTALLEXT/${BldType}/g" <$current/WickrIOCSvr.script > $svcinitdir/WickrIOCSvr$BldType

# systemd service unit files
sed -e "s/EXTENSION/${bldtype}/g" -e "s/INSTALLEXT/${BldType}/g" <$current/WickrIOCSvr.service > $systemdlibdir/WickrIOCSvr$BldType.service
sed -e "s/EXTENSION/${bldtype}/g" -e "s/INSTALLEXT/${BldType}/g" <$current/WickrIOSvr.service > $systemdlibdir/WickrIOSvr$BldType.service

#
# Copy the library files
#
cp -a $platform/*.so $platform/*.so.* $libdir/
rm -f $plugins/sqldrivers/*
#mkdir -p $messages
#echo "/usr/share/applications/wickrio${bldtype}.client" >$messages/wickrio${bldtype}

#
# Generate the MD5 SUM value
#
cd $prefix
find . -type f ! -regex '.*?debian-binary.*' ! -regex '.*?DEBIAN.*' -printf '%P ' | xargs md5sum > DEBIAN/md5sums

#
# Change the mode of the installed files
#
cd ~/tmp
chmod 0644 $debian/*
chmod -R g-w $prefix/usr
chmod -x $libdir/*.so*
chmod 755 $debian/preinst
chmod 755 $debian/postinst
chmod 755 $debian/prerm
chmod 755 $svcinitdir/WickrIOSvr$BldType
chmod 755 $svcinitdir/WickrIOCSvr$BldType
chmod 644 $optdir/WickrIOSvr$BldType.ini
chmod 755 $systemdlibdir/WickrIOSvr$BldType.service
chmod 755 $systemdlibdir/WickrIOCSvr$BldType.service

#
# Create the actual package
#
rm -f wio_services${bldtype}_*.deb
fakeroot chown -R root:root $prefix
chmod 4755 $bindir/WickrIOConsole$BldType

fakeroot dpkg -b wio_services${bldtype}-deb/ wio_services${bldtype}_${version}_amd64.deb
sha256sum wio_services${bldtype}_${version}_amd64.deb >wio_services${bldtype}_${version}_amd64.sha256

if test -d "$output_dir" ; then
    cp wio_services${bldtype}_${version}_amd64.* "$output_dir/" ; fi

