#!/bin/bash

set -e

case "$1" in
    configure)
        echo "Post-install configure for new version of WickrIO:"

        # Definitions of the .INI files
        inifile="/opt/WickrIOINSTALLEXT/WickrIOSvrINSTALLEXT.ini"
        tempdir=/opt/WickrIOINSTALLEXT/temp
        tempinifile="/opt/WickrIOINSTALLEXT/temp/WickrIOSvrINSTALLEXT.ini"

        # if there is a saved INI file then use it
        if [ -f $tempinifile ]
        then
          mv $tempinifile $inifile
        fi

        #
        # Do any pre-execution setup
        #
        wickrio_settings_initEXTENSION /opt/WickrIOINSTALLEXT

        #
        # Start the WickrIO Client service
        #
        set +e
        # Enable the service
        # TODO: Need to make sure the service needs to be enabled
        systemctl enable WickrIOSvrINSTALLEXT

        if [ -f $tempdir/svrstate ]; then
            svrstate=`cat $tempdir/svrstate`
            if [ $svrstate -eq 0 ]; then
                systemctl start WickrIOSvrINSTALLEXT
            fi
            rm $tempdir/svrstate
        fi

        # Add the service(s) to the list of startup services
#        update-rc.d WickrIOSvrINSTALLEXT defaults

        #
        # Start the WickrIO Console service
        #
        set +e
        # Enable the service
        # TODO: Need to make sure the service needs to be enabled
        systemctl enable WickrIOCSvrINSTALLEXT

        if [ -f $tempdir/consvrstate ]; then
            consvrstate=`cat $tempdir/consvrstate`
            if [ $consvrstate -eq 0 ]; then
                systemctl start WickrIOCSvrINSTALLEXT
            fi
            rm $tempdir/consvrstate
        fi

        # Remove the startup entry for the service(s)
#        update-rc.d -f WickrIOCSvrINSTALLEXT defaults
        set -e

    ;;
esac

exit 0
