#!/bin/sh

# a second stage deploy script...

set -e
current=`dirname $0`
cd $current

QTVER="5_7"

BUILDDIR=../../../../../../build-wickr-wickrio-Desktop_Qt_${QTVER}_GCC_64bit_BUILT-QA
build_number=`cat ../../../BUILD_NUMBER`

$current/deploy64 $BUILDDIR $build_number qa QA false $1
