#!/bin/sh

# a second stage deploy script...
#
# Arguments to this script:
# $1 = build number
# $2 = Output directory

set -e
current=`dirname $0`
cd $current

build_number=$1
integrations_output_dir="$2"
output_dir="$3"

#
# Make sure the version number is the correct length
#
check=${#build_number}
if [ $check -lt 8 ]; then
  build_number="0$build_number"
fi

#
# Debug display of input
#
echo build_number=$build_number
echo integrations_output_dir=$integrations_output_dir

#
# Setup the version number(s)
#
maj=`echo $build_number | cut -c1-2 | sed 's/^0*//'`
min=`echo $build_number | cut -c3-4`
pat=`echo $build_number | cut -c5-6`
bld=`echo $build_number | cut -c7-8`

version="${maj}.${min}.${pat}-${bld}"

#
# More debug output
#
echo version=$version

prefix=~/tmp/wio_nodejs_samples
dst_sample_dir=$prefix/nodejs_samples

tar_file=$prefix/WickrIO_nodejs_samples_${version}.tar.gz

# Cleanup the target location (i.e. remove the target directory)
rm -rf $prefix

# Create the appropriate directories in the target location
mkdir -p $dst_sample_dir

#
# Create the sample software tree
#
mkdir -p $dst_sample_dir/wickrio_addon
cp ../wickrio_addon/CMakeLists.txt $dst_sample_dir/wickrio_addon
cp ../wickrio_addon/package.json $dst_sample_dir/wickrio_addon
mkdir -p $dst_sample_dir/wickrio_addon/src
cp ../wickrio_addon/src/bot_iface_node.cpp $dst_sample_dir/wickrio_addon/src
cp -R ../samples $dst_sample_dir
cp ../README.md $dst_sample_dir

#
# Create and copy the appropriate exports
#
mkdir -p ${dst_sample_dir}/exports/libs
mkdir -p ${dst_sample_dir}/exports/include
cp ../../../clients/libs/WickrIOClientAPI/build/libWickrIOClientAPI.a ${dst_sample_dir}/exports/libs
cp ../../../clients/libs/WickrIOClientAPI/src/bot_iface.h ${dst_sample_dir}/exports/include

#
# Create the importable software images for each of the samples. These can be used in
# the WickrIO system, and used as examples of how to import custom integrations.
#
mkdir -p $dst_sample_dir/imports
samples_dir=$current/../samples

compliance_bot_sample=$samples_dir/compliance_bot
if test -f "$compliance_bot_sample/generate.sh" ; then
    echo "generating software.tar.gz for compliance_bot sample"
    cd $compliance_bot_sample
    mkdir $samples_dir/compliance_bot
    ./generate.sh $samples_dir/compliance_bot

    # generate into the integrations output directory
    mkdir -p $integrations_output_dir/compliance_bot
    ./generate.sh $integrations_output_dir/compliance_bot

    cd $current
fi

file_bot_sample=$samples_dir/file_bot
if test -f "$file_bot_sample/generate.sh" ; then
    echo "generating software.tar.gz for file_bot sample"
    cd $file_bot_sample
    mkdir $samples_dir/file_bot
    ./generate.sh $samples_dir/file_bot

    # generate into the integrations output directory
    mkdir -p $integrations_output_dir/file_bot
    ./generate.sh $integrations_output_dir/file_bot

    cd $current
fi

welcome_bot_sample=$samples_dir/welcome_bot
if test -f "$welcome_bot_sample/generate.sh" ; then
    echo "generating software.tar.gz for welcome_bot sample"
    cd $welcome_bot_sample
    mkdir $samples_dir/welcome_bot
    ./generate.sh $samples_dir/welcome_bot

    # generate into the integrations output directory
    mkdir -p $integrations_output_dir/welcome_bot
    ./generate.sh $integrations_output_dir/welcome_bot

    cd $current
fi


#
# Create the actual package
#
cd ${dst_sample_dir}
tar -zcvf ${tar_file} *

#
# copy to the output directory
#
if test -d "$output_dir" ; then
    cp ${tar_file} "$output_dir/"
    echo "copying ${tar_file}.* to $output_dir/"
fi
