#!/bin/sh

# a second stage deploy script...
#
# Arguments to this script:
# $1 = build number
# $2 = integrations output directory
# $3 = Output directory
# $4 = Image type "wickrio" or "welcome"

set -e
current=`dirname $0`
cd $current
pwd=`pwd`

build_number=$1
integrations_output_dir="$2"
output_dir="$3"
image_type="$4"

#
# Make sure the version number is the correct length
#
check=${#build_number}
if [ $check -lt 8 ]; then
  build_number="0$build_number"
fi

#
# Debug display of input
#
echo build_number=$build_number
echo integrations_output_dir=$integrations_output_dir
echo output_dir=$output_dir
echo image_type=$image_type

#
# Setup the version number(s)
#
maj=`echo $build_number | cut -c1-2 | sed 's/^0*//'`
min=`echo $build_number | cut -c3-4`
pat=`echo $build_number | cut -c5-6`
bld=`echo $build_number | cut -c7-8`

version="${maj}.${min}.${pat}-${bld}"

#
# More debug output
#
echo version=$version

prefix=~/tmp/wio_nodejs_samples
dst_sample_dir=$prefix/nodejs_samples

tar_file=$prefix/WickrIO_nodejs_samples_${version}.tar.gz

# Cleanup the target location (i.e. remove the target directory)
rm -rf $prefix

# Create the appropriate directories in the target location
mkdir -p $dst_sample_dir

#
# Create the sample software tree
#
mkdir -p $dst_sample_dir/wickrio_addon
cp ../wickrio_addon/CMakeLists.txt $dst_sample_dir/wickrio_addon
cp ../wickrio_addon/package.json $dst_sample_dir/wickrio_addon
mkdir -p $dst_sample_dir/wickrio_addon/src
cp ../wickrio_addon/src/bot_iface_node.cpp $dst_sample_dir/wickrio_addon/src
cp -R ../samples $dst_sample_dir
cp ../README.md $dst_sample_dir

#
# Create and copy the appropriate exports
#
mkdir -p ${dst_sample_dir}/exports/libs
mkdir -p ${dst_sample_dir}/exports/include
cp ../../../clients/libs/WickrIOClientAPI/build/libWickrIOClientAPI.a ${dst_sample_dir}/exports/libs
cp ../../../clients/libs/WickrIOClientAPI/src/bot_iface.h ${dst_sample_dir}/exports/include

#
# copy the sample config file
#
if [ "$image_type" = "wickrio" ]; then
  cp $pwd/../docs/sample_config.ini ${dst_sample_dir}
fi

#
# Create the importable software images for each of the samples. These can be used in
# the WickrIO system, and used as examples of how to import custom integrations.
#
samples_dir=$pwd/../samples

#compliance_bot_sample=$samples_dir/compliance_bot
#if test -f "$compliance_bot_sample/generate.sh" ; then
#    echo "generating software.tar.gz for compliance_bot sample"
#    mkdir -p $dst_sample_dir/imports/compliance_bot
#    cd $compliance_bot_sample
#    ./generate.sh $dst_sample_dir/imports/compliance_bot
#
#    # generate into the integrations output directory
#    mkdir -p $integrations_output_dir/compliance_bot
#    ./generate.sh $integrations_output_dir/compliance_bot
#
#    cd $pwd
#fi

if [ "$image_type" = "wickrio" ]; then
  file_bot_sample=$samples_dir/file_bot
  if test -f "$file_bot_sample/generate.sh" ; then
      echo "generating software.tar.gz for file_bot sample"
      mkdir -p $dst_sample_dir/imports/file_bot
      cd $file_bot_sample
      ./generate.sh $dst_sample_dir/imports/file_bot

      # generate into the integrations output directory
      mkdir -p $integrations_output_dir/file_bot
      ./generate.sh $integrations_output_dir/file_bot

      cd $pwd
  fi

  hello_world_bot_sample=$samples_dir/hello_world_bot
  if test -f "$hello_world_bot_sample/generate.sh" ; then
      echo "generating software.tar.gz for hello_world_bot sample"
      mkdir -p  $dst_sample_dir/imports/hello_world_bot
      cd $hello_world_bot_sample
      ./generate.sh $dst_sample_dir/imports/hello_world_bot

      # generate into the integrations output directory
      mkdir -p $integrations_output_dir/hello_world_bot
      ./generate.sh $integrations_output_dir/hello_world_bot

      cd $pwd
  fi

  nodejs_dir=$pwd/..

  web_interface=$nodejs_dir/web_interface
  if test -f "$web_interface/generate.sh" ; then
      echo "generating software.tar.gz for web_interface"
      mkdir -p  $dst_sample_dir/imports/web_interface
      cd $web_interface
      ./generate.sh $dst_sample_dir/imports/web_interface

      # generate into the integrations output directory
      mkdir -p $integrations_output_dir/web_interface
      ./generate.sh $integrations_output_dir/web_interface

      cd $pwd
  fi
fi

if [ "$image_type" = "wickrio" ]; then
  welcome_bot_sample=$samples_dir/welcome_bot
  if test -f "$welcome_bot_sample/generate.sh" ; then
      echo "generating software.tar.gz for welcome_bot sample"
      mkdir -p  $dst_sample_dir/imports/welcome_bot
      cd $welcome_bot_sample
      ./generate.sh $dst_sample_dir/imports/welcome_bot

      # generate into the integrations output directory
      mkdir -p $integrations_output_dir/welcome_bot
      ./generate.sh $integrations_output_dir/welcome_bot

      cd $pwd
  fi
fi

#
# Create the actual package
#
cd ${dst_sample_dir}
tar -zcvf ${tar_file} *

#
# copy to the output directory
#
if test -d "$output_dir" ; then
    cp ${tar_file} "$output_dir/"
    echo "copying ${tar_file}.* to $output_dir/"
fi
